services:
  - type: web
    name: jarvis
    repo: https://github.com/Loki-Xer/jarvis.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        sync: false
        required: true
      - key: SUDO
        sync: false
        required: false
      - key: WORK_TYPE
        sync: false
        required: false
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
        
